import { StateGraph, START, END, Annotation } from "@langchain/langgraph";
import { mistralAIModel, cohereModel, geminiModel } from "./ai.model.js";
import { HumanMessage } from "@langchain/core/messages";
import z from 'zod';

const GraphState = Annotation.Root({
    problem: Annotation<string>(),
    solution_1: Annotation<string>(),
    solution_2: Annotation<string>(),
    judge: Annotation<{
        solution_1_score: number;
        solution_2_score: number;
        solution_1_reasoning: string;
        solution_2_reasoning: string;
    }>(),
});

const solutionNode = async (state: typeof GraphState.State) => {
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ]);
    
    // Ensure responses are strings
    const s1 = typeof mistralResponse.content === 'string' ? mistralResponse.content : JSON.stringify(mistralResponse.content);
    const s2 = typeof cohereResponse.content === 'string' ? cohereResponse.content : JSON.stringify(cohereResponse.content);

    return {
        solution_1: s1,
        solution_2: s2
    };
};

const judgeNode = async (state: typeof GraphState.State) => {
    const { problem, solution_1, solution_2 } = state;

    const judgeModel = geminiModel.withStructuredOutput(z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
    }));

    const systemPrompt = "You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.";
    
    const judgeResponse = await judgeModel.invoke([
        { role: "system", content: systemPrompt },
        { role: "user", content: `Problem: ${problem}\nSolution 1: ${solution_1}\nSolution 2: ${solution_2}` }
    ]);

    return {
        judge: judgeResponse
    };
};

const graph = new StateGraph(GraphState)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile();

export default async function (problem: string) {
    const result = await graph.invoke({
        problem: problem
    });

    return result;
}